[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom headers for caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  # Cache images for 1 week
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"
# Add more image types if needed

[dev]
  command = "npm run dev"
  framework = "#custom"
  targetPort = 5173
  port = 8888
  publish = "dist"
