[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {type = "path", splat = true,  to = "\\.((?!js|css|png|jpe?g|gif|svg|ico|woff2|woff|eot|ttf|otf).)*$"}