[build]
  command = "npm install && npm run build"
  functions = "serverless"
  publish = "server/public"

[[redirects]]
  from = "/api/feeds/rss"
  to = "/ai-news-feed.xml"
  status = 200
  force = true

[[redirects]]
  from = "/newsletter"
  to = "/newsletter-subscribe.html"
  status = 200