[build]
  command = "npm run build"
  publish = "dist"

# API Endpoints for subscription and feedback
[[redirects]]
  from = "/api/subscribe"
  to = "/.netlify/functions/subscribe"
  status = 200

[[redirects]]
  from = "/api/feedback"
  to = "/.netlify/functions/feedback"
  status = 200