[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers - Applied to all pages
[[headers]]
  for = "/*"
  [headers.values]
    # Strict Transport Security (HSTS) - Forces HTTPS connections
    # Removed 'preload' to ensure better compatibility with security scanners
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    
    # Content Security Policy (CSP) - Enhanced security, removed unsafe-eval
    # Separated script-src and style-src for better control
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://ssl.google-analytics.com https://www.youtube.com https://open.spotify.com https://platform.twitter.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net; img-src 'self' data: https: blob:; media-src 'self' https:; object-src 'none'; frame-src 'self' https://www.youtube.com https://open.spotify.com https://platform.twitter.com; connect-src 'self' https: wss:; base-uri 'self'; form-action 'self';"
    
    # Clickjacking protection
    X-Frame-Options = "SAMEORIGIN"
    
    # MIME type sniffing prevention
    X-Content-Type-Options = "nosniff"
    
    # XSS protection
    X-XSS-Protection = "1; mode=block"
    
    # Referrer policy for privacy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Permissions policy to control browser features
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    
    # Additional security headers
    X-DNS-Prefetch-Control = "off"
    X-Download-Options = "noopen"
    X-Permitted-Cross-Domain-Policies = "none"

# Custom headers for caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  # Cache images for 1 week
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"
# Add more image types if needed

[dev]
  command = "npm run dev"
  framework = "#custom"
  targetPort = 5173
  port = 8888
  publish = "dist"
