name: RSS Feed Automation

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  rss-feed-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'server/package.json'

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Update RSS and JSON feeds
        run: |
          cd server
          node -e "import('./services/rssFeedService.js').then(({updateFeeds}) => updateFeeds())"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

      - name: Commit and push updated feeds
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add server/public/ai-news-feed.xml server/public/ai-news-feed.json
          git commit -m "Update AI news feeds [skip ci]" || echo "No changes to commit"
          git push
