name: AI Newsletter Automation

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  newsletter-automation:
    runs-on: ubuntu-latest
    # Define secrets at the job level
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'server/package.json'

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Debug Secrets Availability
        run: |
          echo "Checking secrets availability in runner environment..."
          if [ -n "$GEMINI_API_KEY" ]; then echo "GEMINI_API_KEY: Set"; else echo "GEMINI_API_KEY: NOT SET"; fi
          if [ -n "$NEWS_API_KEY" ]; then echo "NEWS_API_KEY: Set"; else echo "NEWS_API_KEY: NOT SET"; fi
          if [ -n "$SUPABASE_URL" ]; then echo "SUPABASE_URL: Set"; else echo "SUPABASE_URL: NOT SET"; fi
          if [ -n "$SUPABASE_ANON_KEY" ]; then echo "SUPABASE_ANON_KEY: Set"; else echo "SUPABASE_ANON_KEY: NOT SET"; fi
          if [ -n "$EMAIL_USER" ]; then echo "EMAIL_USER: Set"; else echo "EMAIL_USER: NOT SET"; fi
          if [ -n "$EMAIL_PASS" ]; then echo "EMAIL_PASS: Set"; else echo "EMAIL_PASS: NOT SET"; fi
        # Env block removed from step, will inherit from job

      - name: Send AI Newsletter to Subscribers
        run: |
          cd server
          node send-newsletter.js
        # Env block removed from step, will inherit from job

      - name: Commit and push updated newsletter
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add server/latest-ai-news.html
          git commit -m "Update AI newsletter and send [skip ci]" || echo "No changes to commit"
          git push
