[build]
  # Directory with code to build
  functions = "serverless"
  command = "npm install && npm run build"
  publish = "server/public"

[[redirects]]
  # Redirect RSS feed requests
  from = "/api/feeds/rss"
  to = "/ai-news-feed.xml"
  status = 200
  force = true

[[redirects]]
  # Redirect newsletter subscription page
  from = "/newsletter"
  to = "/newsletter-subscribe.html"
  status = 200
